In [2]:
import numpy as np
g=np.array([[0,1,0,0,0,0,0,1,0,0],[1,0,0,0,1,0,0,0,0,0],[0,0,0,0,1,0,0,0,0,0],[0,0,0,0,0,1,1,0,0,0],[0,1,1,0,0,1,0,0,0,0],[0,0,0,1,1,0,0,1,1,0],[0,0,0,1,0,0,0,0,0,1],[1,0,0,0,0,1,0,0,0,0],[0,0,0,0,0,1,0,0,0,1],[0,0,0,0,0,0,1,0,1,0]])
print(g)

[[0 1 0 0 0 0 0 1 0 0]
 [1 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 1 1 0 0 0]
 [0 1 1 0 0 1 0 0 0 0]
 [0 0 0 1 1 0 0 1 1 0]
 [0 0 0 1 0 0 0 0 0 1]
 [1 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 1]
 [0 0 0 0 0 0 1 0 1 0]]


In [3]:
mndis=np.array([50,40,30,20,30,20,10,30,20,0])
print(mndis)

[50 40 30 20 30 20 10 30 20  0]


In [4]:
op={}
def func(node):
    for i in range(10):
        if(g[node][i]==1):
            op.update({i:mndis[i]})
    sorted_dict = {}
    sorted_keys = sorted(op, key=op.get)
    for w in sorted_keys:
        sorted_dict[w] = op[w]
    return sorted_dict

In [5]:
queue={7:30,1:40}
stack={0:50}
print(queue.keys)
for i in range(10):
    print(queue,"queue")
    print(stack,"explored")
    curentnode=list(queue.keys())[0]
    stack[curentnode]=queue[curentnode]
    del queue[curentnode]
    t=func(curentnode)
    f=set(list(t.keys()))
    s=set(list(stack.keys()))
    k=list(f-s.intersection(f))
    for j in k:
        queue[j]=t[j]

    sorted_dict = {}
    sorted_keys = sorted(queue, key=queue.get)
    for w in sorted_keys:
        sorted_dict[w] = queue[w]
    queue=sorted_dict   
    #node ke acjo age ke frontier honge unko sorted list
    #usko queue me dal do
    
    #stack ko update kerdo currentnode se
    if(curentnode==9):
        break


<built-in method keys of dict object at 0x114c8d820>
{7: 30, 1: 40} queue
{0: 50} explored
{5: 20, 1: 40} queue
{0: 50, 7: 30} explored
{8: 20, 3: 20, 4: 30, 1: 40} queue
{0: 50, 7: 30, 5: 20} explored
{9: 0, 3: 20, 4: 30, 1: 40} queue
{0: 50, 7: 30, 5: 20, 8: 20} explored
